// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 head: "Turismo CF 900",
 subhead: "Turismo CF 500",
 base: "Ubuntu",
 code: "Ubuntu Mono"
}

export default fontFamilies;