// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "green": "rgba(15, 169, 88, 1)",
 "blue": "rgba(0, 41, 255, 1)",
 "yellow": "rgba(255, 199, 0, 1)",
 "ocean": "rgba(0, 209, 222, 1)",
 "red": "rgba(254, 24, 24, 1)",
 "violet": "rgba(123, 97, 255, 1)",
 "gray700": "rgba(131, 131, 131, 1)",
 "white": "rgba(255, 255, 255, 1)",
 "black": "rgba(0, 0, 0, 1)"
}

export default colors;