// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "small": "0.75rem",
 "base": "1rem",
 "baseL": "1.13rem",
 "sub": "1.5rem",
 "h": "2.25rem",
 "hL": "2.63rem",
 "hxl": "3.38rem",
 "hXxl": "3.88rem"
}

export default fontSizes;