// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
 "extraWhide": "0.08em",
 "whideI": "0.05em",
 "whide": "0.03em",
 "normal": "0em",
 "thin": "-0.03em",
 "thinI": "-0.05em",
 "extraThin": "-0.08em"
}

export default letterSpacings;