// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const lineHeights = {
 "lh165": "1.65",
 "lh150": "1.50",
 "lh135": "1.35",
 "lh120": "1.20",
 "lh100": "1.00",
}

export default lineHeights;