// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 mobileSm: "320px",
 mobileMax: "640px",
 tablet: "960px",
 desktop: "1180px",
 wide: "1920px"
}

export default mediaQueries;