// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const shadows = {
 "shadRed": "2px 2px 0px rgba(0, 0, 0, 1), 10px 10px 0px rgba(254, 24, 24, 1)",
 "shadBlue": "2px 2px 0px rgba(0, 0, 0, 1), 10px 10px 0px rgba(0, 41, 255, 1)",
 "shadYell": "2px 2px 0px rgba(0, 0, 0, 1), 10px 10px 0px rgba(255, 199, 0, 1)",
 "shad400": "6px 6px 0px rgba(0, 0, 0, 1)",
 "shad200": "4px 4px 0px rgba(0, 0, 0, 1)",
 "shad100": "2px 2px 0px rgba(0, 0, 0, 1)"
}

export default shadows;