// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 huge: "4rem",
 large: "3rem",
 big: "2.25rem",
 normal: "1.5rem",
 small: "1rem",
 xsml: "0.5rem"
}

export default spacing;